seed: 1337

project: unet-oxford-pet
p_train_len: 0.9

# model and loss
in_channels: 3
out_channels: 3
weights: [1.3, 1.0, 0.0]
ignore_index: 2


p_dropout: 0.1

# Optimizer
lr: 1e-4
enc_lr: 1e-4
dec_lr: 1e-3
weight_decay: 1e-5

# LR scheduler
t0: 10
tmult: 2
eta_min: 1e-6

add_augmentation: True
train_enhanced: False