name: unet-local

batch_size: 8
image_size: 224
n_epochs: 7
device: cpu
data_root: /Users/justinbarry/projects/unet/data/

test_run: True
sample_size: 400
wandb_mode: disabled

visualize_predictions: False
num_workers: 4

test_model: False
train_model: True
artifact_name: jbarry-team/unet-oxford-pet/unet-server-batch-norm_best_model:latest
save_model: False
