name: unet-local

batch_size: 8
image_size: 224
n_epochs: 7
device: cpu
data_root: /Users/justinbarry/projects/unet/data/

test_run: True
sample_size: 40
wandb_mode: disabled

visualize_predictions: False
num_workers: 4

test_model: True
train_model: False
save_model: False

artifact_name: jbarry-team/unet-oxford-pet/resnetunet-add-augmentation-enhanced_best_model:latest
# artifact_name: jbarry-team/unet-oxford-pet/resnetunet-save-new-train-val-laoder_best_model:latest

# Unfreeze encoder parameters
unfreeze_stage0: 3
unfreeze_stage1: 4
