name: unet-local

batch_size: 4
image_size: 128
n_epochs: 7
device: cpu
data_root: /Users/justinbarry/projects/unet/data/

test_run: True
sample_size: 20
wandb_mode: disabled

visualize_predictions: True
num_workers: 4

test_model: False
train_model: True
