name: resnetunet-add-augmentation-unenhanced

batch_size: 32
image_size: 224
n_epochs: 40
device: cuda
data_root: /workspace/unet/data

test_run: False
wandb_mode: online

visualize_predictions: False
num_workers: 15

test_model: False
train_model: True
save_model: True

# Unfreeze encoder parameters
unfreeze_stage0: 6
unfreeze_stage1: 10