name: unet-server-dropout-lrscheduler

n_epochs: 40
device: cuda
data_root: /workspace/unet/data

test_run: False
wandb_mode: online

visualize_predictions: False
num_workers: 15

test_model: False
train_model: True
save_model: False
