name: unet-server

batch_size: 32
image_size: 224
n_epochs: 100
device: cuda
data_root: /workspace/unet/data

test_run: False
wandb_active: online

visualize_predictions: False
num_workers: 15

test_model: False
train_model: True
